### PR TITLE
validate happy path test

### PR DESCRIPTION
**Pull request by mattkim93**
To address this convo: https://washpost.slack.com/archives/GEPU58ABD/p1551468844025400

Adds assertions to ruleset happy path test to ensure we are not rendering an error message & application state.

Currently, the API is returning an error, so this test is failing as intended.

### CODE REVIEW

**Comment by mattkim93** [comment]
@merwan7 yep, makes sense. I don't think we'd want this out before the API fix either, since jenkins will start yelling at us haha. I'll keep it open until Monday.

**Comment by Ahmedz1984** [comment]
Thank you Matt, Really appreciate. I will make sure next time.

**Comment by Ahmedz1984** [comment]
As we talked @merwan7 @mattkim93 @haganka 

I am seeing the issue to added this code in automation. The issue is that each time when the test run even test is able to create the ruleset via automation, it will look for this error message. 
I am going to make the changes as below. 
After create the rulesets 
Script will go to the index page and take a look that particular rulesets are created or not. If it's not created the particular rulesets test will going to failed. 
Please let me know, if there is a any concern with above steps. 
cc: @nalreja

**Comment by merwan7** [comment]
closing this since it was resolved another way

**Pull request closed without merging**
